name: getxfire
description: A Flutter project that implemented getx package and firebase services.
version: 0.0.2
homepage: https://github.com/faisalramdan17/getxfire/wiki
repository: https://github.com/faisalramdan17/getxfire

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Firebase Packages
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  # firebase_messaging: ^9.1.4 # Coming Soon
  firebase_dynamic_links: ^2.0.3
  firebase_analytics: ^8.0.4

  # SignIn Packages
  google_sign_in: ^5.0.4
  # flutter_facebook_auth: ^3.4.0 # Coming Soon
  sign_in_with_apple: ^3.0.0 # Coming Soon

  # Utils Packages
  dio: ^4.0.0
  image_picker: ^0.7.5+3
  permission_handler: ^8.0.0+2
  flutter_image_compress: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  location: ^4.1.1
  geoflutterfire: ^3.0.0-nullsafety.4
  rxdart: ^0.27.0 # Needs to be updated when geoflutterfire changes.
  crypto: ^3.0.1 # md5 on chat, facebook  login
  algolia: ^1.0.1
  merge_map: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: id.codingyourlife.getxfire
        pluginClass: GetxfirePlugin
      ios:
        pluginClass: GetxfirePlugin
      web:
        pluginClass: GetxfireWeb
        fileName: getxfire_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
